name: Build Front

on:
  push:
    branches:
      - master
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'

env:
  DOCKERHUB_REPOSITORY: dlike/insure-agent-front

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dlike
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG -t $DOCKERHUB_REPOSITORY:latest ./front
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
          docker push $DOCKERHUB_REPOSITORY:latest
